# Use an official Python runtime as a parent image
FROM python:3.9-alpine

# Install dependencies
RUN apk add --no-cache \
    build-base \
    linux-headers \
    pcre-dev \
    libressl-dev \
    musl-dev \
    libffi-dev

# Set the working directory in the container
WORKDIR /usr/src/app

# Copy the current directory contents into the container at /usr/src/app
COPY . .

# Install any needed packages specified in requirements.txt
RUN pip install redis numpy
# Make port 6379 available to the world outside this container
EXPOSE 6379

# Run main.py when the container launches
CMD ["python", "main.py"]
